//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pizza_db.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pizza_db.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7f95348d_7a64_4d96_8f1b_8f7ffca37f66 {
            get {
                object obj = ResourceManager.GetObject("7f95348d-7a64-4d96-8f1b-8f7ffca37f66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap เฟรนฟราย {
            get {
                object obj = ResourceManager.GetObject("เฟรนฟราย", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap พิซซ่าหน้าเลิฟเวอร์_สุพรีม__Pizza_Lovers_Supreme_ {
            get {
                object obj = ResourceManager.GetObject("พิซซ่าหน้าเลิฟเวอร์ สุพรีม (Pizza Lovers Supreme)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap พิซซ่าหน้ากะเพราไก่__Pizza_Ka_Prao_Chicken_ {
            get {
                object obj = ResourceManager.GetObject("พิซซ่าหน้ากะเพราไก่ (Pizza Ka Prao Chicken)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap พิซซ่าหน้าชิกเก้น_ดูโอ__Pizza_Chicken_Duo_ {
            get {
                object obj = ResourceManager.GetObject("พิซซ่าหน้าชิกเก้น ดูโอ (Pizza Chicken Duo)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap พิซซ่าหน้าซอสเซส_ไอซ์แลนด์__Pizza_Sausage_Island_ {
            get {
                object obj = ResourceManager.GetObject("พิซซ่าหน้าซอสเซส ไอซ์แลนด์ (Pizza Sausage Island)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap พิซซ่าหน้าซีฟู้ด__Pizza_Seafood_ {
            get {
                object obj = ResourceManager.GetObject("พิซซ่าหน้าซีฟู้ด (Pizza Seafood)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap พิซซ่าหน้าต้มยำซีฟู้ด__Pizza_Tomyum_Seafood_ {
            get {
                object obj = ResourceManager.GetObject("พิซซ่าหน้าต้มยำซีฟู้ด (Pizza Tomyum Seafood)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap พิซซ่าหน้าผักโขม__Pizza_Spinach_Cheese_ {
            get {
                object obj = ResourceManager.GetObject("พิซซ่าหน้าผักโขม (Pizza Spinach Cheese)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap พิซซ่าหน้าพอร์คพาเหรด__Pizza_Pork_Parade_ {
            get {
                object obj = ResourceManager.GetObject("พิซซ่าหน้าพอร์คพาเหรด (Pizza Pork Parade)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap พิซซ่าหน้ามัสมั่นทูน่า__Pizza_Massaman_ {
            get {
                object obj = ResourceManager.GetObject("พิซซ่าหน้ามัสมั่นทูน่า (Pizza Massaman)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap พิซซ่าหน้าฮาวายเอี้ยน__Pizza_Hawaiian_ {
            get {
                object obj = ResourceManager.GetObject("พิซซ่าหน้าฮาวายเอี้ยน (Pizza Hawaiian)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
